version: "3.7"
services:
  api:
    image: code-test:dev
    build:
      target: dev
    environment:
      - NODE_ENV=development
      - APP_ENV=development
      - LOG=debug
    volumes:
      - ./:/app
      - /app/node_modules/
