version: "3.7"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wisely_test
    ports:
      - "5432:5432"
  api:
    image: code-test:prod
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    environment:
      - DATABASE_CONNECTION_STRING=postgres://postgres:password@db/wisely_test
      - NODE_ENV=production
      - APP_ENV=production
      - PORT=8080
      - LOG=info
    depends_on:
      - db
    ports:
      - "9090:8080"
